# -*- coding: utf-8 -*-
"""objective.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZYvL-N3bCqZrhjMqum0vaIBpbOuBU1lS
"""

import nltk
nltk.download('punkt')

def objective(sample1, sample2):
    import nltk
    from nltk.tokenize import word_tokenize, sent_tokenize

    ans = {}

    with open (sample1) as f:
        Lines = f.readlines()
        for line in Lines:
            tokens = sent_tokenize(line)
            ans[tokens[0]]=tokens[1]

    print(ans)

    import nltk
    from nltk.tokenize import word_tokenize, sent_tokenize

    file_docs = {}

    with open (sample2) as f:
        Lines = f.readlines()
        for line in Lines:
            tokens = sent_tokenize(line)
            file_docs[tokens[0]]=tokens[1]

    print(file_docs)

    correct={}
    for j in file_docs:
        for i in ans:
            if(i==j):
                if(type(ans[i])==list):
                    for k in range(len(ans[i])):
                        if(ans[i][k]==file_docs[j]):
                            correct[i]=file_docs[j]
                else:
                    if(file_docs[j]==ans[i]):
                        correct[i]=file_docs[j]
    score = (len(correct)/len(file_docs))*100
    print(correct)
    print(score)
    return score