# Generated by Django 3.1.7 on 2021-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_answer',
            name='score',
            field=models.CharField(default=20, max_length=255),
            preserve_default=False,
        ),
    ]
